export const PRODUCTS = [
    {
        id: 1,
        name: "Classic White Bear",
        price: 29.99,
        category: "Mini Teddies",
        image: "/images/cute.webp",
    },
    {
        id: 2,
        name: "Romantic Gift Plush",
        price: 34.99,
        category: "Romantic",
        image: "/images/gift.jpg",
    },
    {
        id: 3,
        name: "Little Cutie Bear",
        price: 39.99,
        category: "Classic",
        image: "/images/cutie.webp",
    },
    {
        id: 4,
        name: "Playful Green Dragon",
        price: 44.99,
        category: "Dragons",
        image: "/images/poster.webp",
    },
    {
        id: 5,
        name: "Sleepy Brown Bear",
        price: 32.99,
        category: "Classic",
        image: "/images/sleep-bear.jpg",
    },
    {
        id: 6,
        name: "Fluffy Unicorn Plush",
        price: 49.99,
        category: "Magical",
        image: "/images/fluff-unicorn.jpg",
    },
    {
        id: 7,
        name: "Snuggly Koala",
        price: 38.99,
        category: "Exotic",
        image: "/images/snug-koala.jpg",
    },
    {
        id: 8,
        name: "Giant Teddy Cuddle",
        price: 55.99,
        category: "Giant",
        image: "/images/hero-teddy.jpeg",
    },
    {
        id: 9,
        name: "Big Fluff Bunny",
        price: 52.99,
        category: "Giant",
        image: "/images/giant-bunny.webp",
    },
    { id: 10, name: "Premium Mocha Bear", price: 65.00, category: "Premium", image: "/images/teddy1.jpg" },
    { id: 11, name: "Classic Caramel Bear", price: 42.00, category: "Classic", image: "/images/teddy2.jpg" },
    { id: 12, name: "Snuggle Cocoa Plush", price: 38.50, category: "Classic", image: "/images/teddy3.jpg" },
    { id: 13, name: "Velvet Toffee Hugger", price: 59.99, category: "Velvet", image: "/images/teddy4.jpg" },
    { id: 14, name: "Cloud White Edition", price: 79.99, category: "Limited", image: "/images/teddy5.jpg" },
    { id: 15, name: "Chocolate Swirl Joy", price: 45.00, category: "Premium", image: "/images/teddy6.jpg" },
    { id: 16, name: "Giant Golden Retriever Teddy", price: 89.99, category: "Giant", image: "/images/teddy7.jpg" },
    { id: 17, name: "Winter Grey Sparkle", price: 54.00, category: "Limited", image: "/images/teddy8.jpg" },
    { id: 18, name: "Autumn Maple Cuddler", price: 49.00, category: "Classic", image: "/images/teddy9.jpg" },
    { id: 19, name: "Vanilla Bean Giant", price: 95.00, category: "Giant", image: "/images/teddy10.jpg" },
    { id: 20, name: "Berry Scented Sweetheart", price: 39.99, category: "Classic", image: "/images/teddy11.jpg" },
    { id: 21, name: "Midnight Onyx Bear", price: 69.99, category: "Limited", image: "/images/teddy12.jpg" }
];