export const PRODUCTS = [
    { id: 1, name: "Classic Caramel Bear", price: 2499, oldPrice: 3200, category: "Classic", image: "/images/sleep-bear.jpg" },
    { id: 2, name: "Midnight Shadow Teddy", price: 3499, category: "Premium", image: "/images/hero-teddy.jpeg" },
    { id: 3, name: "Snowdrift White Bear", price: 2999, oldPrice: 4500, category: "Limited", image: "/images/cute.webp" },
    { id: 4, name: "Playful Green Dragon", price: 4499, category: "Dragons", image: "/images/poster.webp" },
    { id: 5, name: "Snug Koala Plush", price: 1999, oldPrice: 2800, category: "Exotic", image: "/images/snug-koala.jpg" },
    { id: 6, name: "Fluffy Unicorn Teddy", price: 2799, category: "Fantasy", image: "/images/fluff-unicorn.jpg" },
    { id: 7, name: "Cuddle Panda", price: 2299, category: "Classic", image: "/images/cutie.webp" },
    { id: 8, name: "Gentle Pink Hugger", price: 2599, oldPrice: 3600, category: "Premium", image: "/images/gift.jpg" },
    { id: 9, name: "Big Fluff Bunny", price: 5499, category: "Giant", image: "/images/giant-bunny.webp" },
    { id: 10, name: "Premium Mocha Bear", price: 4999, oldPrice: 6500, category: "Premium", image: "/images/teddy1.jpg" },
    { id: 11, name: "Classic Caramel Bear", price: 3499, category: "Classic", image: "/images/teddy2.jpg" },
    { id: 12, name: "Snuggle Cocoa Plush", price: 2999, category: "Classic", image: "/images/teddy3.jpg" },
    { id: 13, name: "Velvet Toffee Hugger", price: 3999, oldPrice: 5000, category: "Velvet", image: "/images/teddy4.jpg" },
    { id: 14, name: "Cloud White Edition", price: 5999, category: "Limited", image: "/images/teddy5.jpg" },
    { id: 15, name: "Chocolate Swirl Joy", price: 3299, category: "Premium", image: "/images/teddy6.jpg" },
    { id: 16, name: "Giant Golden Retriever", price: 8999, oldPrice: 12000, category: "Giant", image: "/images/teddy7.jpg" },
    { id: 17, name: "Winter Grey Sparkle", price: 4399, category: "Limited", image: "/images/teddy8.jpg" },
    { id: 18, name: "Autumn Maple Cuddler", price: 3899, category: "Classic", image: "/images/teddy9.jpg" },
    { id: 19, name: "Vanilla Bean Giant", price: 9599, oldPrice: 11000, category: "Giant", image: "/images/teddy10.jpg" },
    { id: 20, name: "Berry Scented Sweetheart", price: 2999, category: "Classic", image: "/images/teddy11.jpg" },
    { id: 21, name: "Midnight Onyx Bear", price: 5499, category: "Limited", image: "/images/teddy12.jpg" }
];